name: auto_size_text_field
description: Flutter TextField widget that automatically resizes text field to fit perfectly within its bounds.
version: 2.2.2
homepage: https://github.com/lzhuor/auto_size_text_field

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
